// app/booth/data.ts
export const MOCK_PROJECTS = [
  {
    project_id: "1",
    title: "純喫茶　ヤスシ",
    type: "class",
    class_id: "2-1",
    location: "4F 401教室",
    description: "昭和の香り漂う「純喫茶 ヤスシ」。\n話題のわらび餅ドリンクをご用意しております。懐かしくも新しいひとときを、ぜひお楽しみください。皆さまのご来店を心よりお待ちしております。",
    image_url: "/images/booth/1.webp", // public/images/booth/ に保存
  },
  {
    project_id: "2",
    title: "長田大脱獄",
    type: "class",
    class_id: "2-2",
    location: "3F 309教室",
    description: "無罪にも関わらず逮捕され送られた先は、一度入ると生還困難と言われる「第165収容所」であった———。 謎を解いて、脱獄せよ。",
    image_url: "/images/booth/2.webp",
  },
  {
    project_id: "3",
    title: "長田生格付けチェック❗️",
    type: "class",
    class_id: "2-3",
    location: "3F 304教室",
    description: "あなたは果たして一流長田生になることはできるのか！？\n \n様々なクイズ、そして、射的に参加して景品を手に入れよう！最高得点者にはとっておきのプレゼントも！？3組一同待ってます❤️",
    image_url: "/images/booth/3.webp",
  },
  {
    project_id: "4",
    title: "巨大迷路",
    type: "class",
    class_id: "2-4",
    location: "4F 403教室", 
    description: "巨大迷路です。色々な仕掛けが発動します。",
    image_url: "/images/booth/4.webp",
  },
  {
    project_id: "5",
    title: "長田総合病院",
    type: "class",
    class_id: "2-5,2-6",
    location: "4F 407・408教室",
    description: "ー誓約書ー\n一、治療における一切の責任を問いません。\n一、医師に治療に関する全てを委ねます。\n一、治療は最期まで受けることを誓います。",
    image_url: "/images/booth/5.webp",
  },
  {
    project_id: "6",
    title: "長者の街 億村",
    type: "class",
    class_id: "2-7",
    location: "3F 301教室",
    description: "2日限りのカジノ、ここに開幕——。知性も運も実力の内。強者のみが高みへ辿り着く。さあ、君はどうだ？勝つか沈むか、その一手にすべてを賭けろ。",
    image_url: "/images/booth/6.webp",
  },
  {
    project_id: "7",
    title: "超ときめき♡ご奉仕部",
    type: "class",
    class_id: "2-8",
    location: "3F 307教室",
    description: "最上級の「かわいい」と「おいしい」でご主人様をお出迎え♡♡\n疲れた時はぜひ「超ときめき♡ご奉仕部」へ",
    image_url: "/images/booth/7.webp",
  },
  {
    project_id: "8",
    title: "チュロス・チーズボール",
    type: "food",
    class_id: "3-1",
    location: "中庭正門側",
    description: "近藤流〜喰うか喰われるか〜\n愛羅武由里香卍\n歪な男女比が生み出した、奇跡の味",
    image_url: "/images/booth/8.webp",
  },
  {
    project_id: "9",
    title: "混ぜそば",
    type: "food",
    class_id: "3-2",
    location: "体育館前",
    description: "♪神のまぜそば辛のまぜそば3の2まぜそばうまいまいまいまい♪\n歴史を刻めんのはこの真のまぜそばを食べたお前だけだ。\n \n神のまぜそば　160円\n辛のまぜそば　180円",
    image_url: "/images/booth/9.webp",
  },
  {
    project_id: "10",
    title: "トモトモチキチキペッパーズ！！(唐揚げ・ポテト)",
    type: "food",
    class_id: "3-3",
    location: "体育館前",
    description: "うまイっちゃってる！！\n佐藤先生も待ってるよ！！ぜひ来てね！！",
    image_url: "/images/booth/10.webp",
  },
  {
    project_id: "11",
    title: "たかえチャン…Kiss More♡",
    type: "food",
    class_id: "3-4",
    location: "中庭西棟側",
    description: "最強の真珠麿喫茶、爆誕⁉︎\n我らが担任こと女神、たかえチャンプロデュースの最高傑作。\n焼きマシュマロやアイス入りスモアパフェが絶品！選べる味は4種類も‼︎\nあなたも一緒にとろけませんか？",
    image_url: "/images/booth/11.webp",
  },
  {
    project_id: "12",
    title: "クレープ…ってコト！？",
    type: "food",
    class_id: "3-5",
    location: "中庭西棟側",
    description: "一口食べれば笑顔になれる！青春の甘さをぎゅっと包みました！甘くて幸せ広がる絶品クレープをぜひ食べてみてください〜！",
    image_url: "/images/booth/12.webp",
  },
  {
    project_id: "13",
    title: "口福横丁",
    type: "food",
    class_id: "3-6",
    location: "体育館前",
    description: "ぜひお立ち寄りください。丁寧に焼き上げた香ばしい串を、心を込めてご提供いたします。お昼のひとときにどうぞ。",
    image_url: "/images/booth/13.webp",
  },
  {
    project_id: "14",
    title: "ANDOO 焼きそば　〜俺か、俺以外か〜",
    type: "food",
    class_id: "3-7",
    location: "中庭正門側",
    description: "担任の安藤先生をはじめとする3-7のイケメンホストたちが姫(お客様)に焼きそばを提供し、No.1を目指します！！",
    image_url: "/images/booth/14.webp",
  },
  {
    project_id: "15",
    title: "炒atHanPT",
    type: "food",
    class_id: "3-8",
    location: "中庭南棟側",
    description: "ーー我々は炒飯を超えた。ーー\n結論から言うね。最適化されたこのチャーハン、めっちゃ美味しい。理由も説明できるけど、まずは食べてみて😊\n👉炒飯　100円\n👉キムチ炒飯　100円\n👉小座本　60円",
    image_url: "/images/booth/15.webp",
  },
];