// app/booth/data.ts
export const MOCK_PROJECTS = [
  {
    project_id: "1",
    title: "わらび餅ドリンク",
    type: "class",
    class_id: "2-1",
    location: "3F 301教室",
    description: "説明文がありません",
    image_url: "/images/booth/1.png", // public/images/booth/ に保存
  },
  {
    project_id: "2",
    title: "長田大脱獄",
    type: "class",
    class_id: "2-2",
    location: "3F 302教室",
    description: "無罪にも関わらず逮捕され送られた先は、一度入ると生還困難と言われる「第165収容所」であった———。 謎を解いて、脱獄せよ。",
    image_url: "/images/booth/2.png",
  },
  {
    project_id: "3",
    title: "縁日/ミニゲーム",
    type: "class",
    class_id: "2-3",
    location: "3F 303教室",
    description: "説明文がありません",
    image_url: "/images/booth/3.png",
  },
  {
    project_id: "4",
    title: "巨大迷路",
    type: "class",
    class_id: "2-4",
    location: "3F 304教室", 
    description: "説明文がありません",
    image_url: "/images/booth/4.png",
  },
  {
    project_id: "5",
    title: "お化け屋敷 5,6組合同",
    type: "class",
    class_id: "2-5,2-6",
    location: "3F 305・306教室",
    description: "説明文がありません",
    image_url: "/images/booth/5.png",
  },
  {
    project_id: "6",
    title: "カジノ",
    type: "class",
    class_id: "2-7",
    location: "3F 307教室",
    description: "説明文がありません",
    image_url: "/images/booth/6.png",
  },
  {
    project_id: "7",
    title: "パンケーキ",
    type: "class",
    class_id: "2-8",
    location: "3F 308教室",
    description: "説明文がありません",
    image_url: "/images/booth/7.png",
  },
  {
    project_id: "8",
    title: "チュロス・チーズボール",
    type: "food",
    class_id: "3-1",
    location: "職員室前テント北側",
    description: "説明文がありません",
    image_url: "/images/booth/8.png",
  },
  {
    project_id: "9",
    title: "混ぜそば",
    type: "food",
    class_id: "3-2",
    location: "職員室前テント南側",
    description: "説明文がありません",
    image_url: "/images/booth/9.png",
  },
  {
    project_id: "10",
    title: "トモトモチキチキペッパーズ！！(唐揚げ・ポテト)",
    type: "food",
    class_id: "3-3",
    location: "校門前テント北側",
    description: "うまイっちゃってる！！\n佐藤先生も待ってるよ！！ぜひ来てね！！",
    image_url: "/images/booth/10.png",
  },
  {
    project_id: "11",
    title: "スモア・焼きマシュマロ",
    type: "food",
    class_id: "3-4",
    location: "校門前テント南側",
    description: "説明文がありません",
    image_url: "/images/booth/11.png",
  },
  {
    project_id: "12",
    title: "クレープ",
    type: "food",
    class_id: "3-5",
    location: "中庭北側テント周り",
    description: "説明文がありません",
    image_url: "/images/booth/12.png",
  },
  {
    project_id: "13",
    title: "口福横丁",
    type: "food",
    class_id: "3-6",
    location: "中庭南側テント周り",
    description: "ぜひお立ち寄りください。丁寧に焼き上げた香ばしい串を、心を込めてご提供いたします。お昼のひとときにどうぞ。",
    image_url: "/images/booth/13.png",
  },
  {
    project_id: "14",
    title: "焼きそば",
    type: "food",
    class_id: "3-7",
    location: "ピロティ東側",
    description: "説明文がありません",
    image_url: "/images/booth/14.png",
  },
  {
    project_id: "15",
    title: "炒atHanPT",
    type: "food",
    class_id: "3-8",
    location: "ピロティ西側",
    description: "ーー我々は炒飯を超えた。ーー\n結論から言うね。最適化されたこのチャーハン、めっちゃ美味しい。理由も説明できるけど、まずは食べてみて😊\n👉炒飯　100円\n👉キムチ炒飯　100円\n👉小座本　60円",
    image_url: "/images/booth/15.png",
  },
];