// app/stage/data.ts

export const STAGE_PROJECTS = [
  {
    project_id: "s1",
    title: "吹奏楽部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 9:30〜10:20\n【2日目】 10:35〜11:25",
    description: "吹奏楽部による圧巻のパフォーマンス！",
    image_url: "/images/stage/s1.png",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s2",
    title: "Specios",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 10:10〜10:30",
    description: "野外ステージを熱く盛り上げます！",
    image_url: "/images/stage/s2.png",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s3",
    title: "放送委員会",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 10:35〜11:05\n【2日目】 9:50〜10:20",
    description: "放送委員会による特別ステージ企画。",
    image_url: "/images/stage/s3.png",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s4",
    title: "演劇部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 11:20〜12:20\n【2日目】 13:05〜14:05",
    description: "『志望理由書』作・いぐりんとその仲間達/舞台は進路指導室。お楽しみに！。",
    image_url: "/images/stage/s4.png",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s5",
    title: "キャサリンのまつげ。",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 12:25〜12:45",
    description: "個性溢れるパフォーマンスをお届けします！",
    image_url: "/images/stage/s5.png",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s6",
    title: "週末ホールディングス",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 12:35〜13:05",
    description: "講堂が笑いと熱気に包まれる！",
    image_url: "/images/stage/s6.png",
    category: "indoor",
    day: 1,
  },
  {
    project_id: "s7",
    title: "IRIS blue",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 13:00〜13:20",
    description: "ナガタソングとスイブステップ",
    image_url: "/images/stage/s7.png",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s8",
    title: "音楽部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 13:20〜14:20\n【2日目】 11:45〜12:45",
    description: "本格的な合唱曲からみんな知ってるJpopまで！文化祭の喧騒を離れて私たちの音楽に耳を傾けてみてはいかがですか？。",
    image_url: "/images/stage/s8.png",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s9",
    title: "Copy Cat",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 14:35〜15:00",
    description: "誰でも知ってるあの曲を！",
    image_url: "/images/stage/s9.png",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s10",
    title: "書道部（パフォーマンス）",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【2日目】 9:20〜9:40",
    description: "書道部による大迫力のパフォーマンス！",
    image_url: "/images/stage/s10.png",
    category: "indoor",
    day: 2,
  },
  {
    project_id: "s11",
    title: "こしあねん",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 9:30〜9:50",
    description: "みんなで一緒に盛り上がりましょう！",
    image_url: "/images/stage/s11.png",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s12",
    title: "nanala",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 10:20〜10:40",
    description: `"君に笑顔の向日葵咲かせたい。"\nあの有名ソングをシャッフルボーカルでお届け🌻\nぜひぜひ足を運んでくださーい！！！"`,
    image_url: "/images/stage/s12.png",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s13",
    title: "ダンス部",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 11:05〜11:45",
    description: "ダンス部による最高のパフォーマンス！",
    image_url: "/images/stage/s13.png",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s14",
    title: "Traverse",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 12:45〜13:05",
    description: "Q.あなたはなぜステージに登るのですか？\nA.なぜって？そこにステージがあるからさ\ntips: 🥂😆　💖⚔️　💎🏝️　🧑‍🤝‍🧑💞",
    image_url: "/images/stage/s14.png",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s15",
    title: "Ousia",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 14:05〜14:30",
    description: "心を揺さぶるパフォーマンス！",
    image_url: "/images/stage/s15.png",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s16",
    title: "lien",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【2日目】 14:35〜14:55",
    description: "説明文がありません",
    image_url: "/images/stage/s16.png",
    category: "indoor",
    day: 2,
  },
  {
    project_id: "s17",
    title: "Milky♡Quint",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【2日目】 14:15〜14:30",
    description: "5人組アイドルステージ✨\n今日限りの最強可愛いミニライブぜひ見に来てください！！",
    image_url: "/images/stage/s17.png",
    category: "indoor",
    day: 2,
  },
];