// app/stage/data.ts

export const STAGE_PROJECTS = [
  {
    project_id: "s1",
    title: "吹奏楽部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 9:30〜10:20\n【2日目】 10:35〜11:25",
    description: "~NBB魔法音楽学校の世界へようこそ~",
    image_url: "/images/stage/s1.webp",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s2",
    title: "Specios",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 10:10〜10:30",
    description: "Speciosとは。それは、あなたがステージで見るすべて。",
    image_url: "/images/stage/s2.webp",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s3",
    title: "放送委員会",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 10:35〜11:05\n【2日目】 9:50〜10:20",
    description: "放送委員会の過去の大会作品を特別上映！\nこれまでに制作してきた力作の数々を一挙公開します。放送委員会の映像の世界をぜひお楽しみください。",
    image_url: "/images/stage/s3.webp",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s4",
    title: "演劇部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 11:20〜12:20\n【2日目】 13:05〜14:05",
    description: "『志望理由書』作・いぐりんとその仲間達/舞台は進路指導室。お楽しみに！。",
    image_url: "/images/stage/s4.webp",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s5",
    title: "キャサリンのまつげ。",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 12:25〜12:45",
    description: `80回生ガールズバンド通称"キャサま" (?)\n個性あるパフォーマンスにぜひご期待ください💥\n一緒に声を出して盛り上がりましょう！！`,
    image_url: "/images/stage/s5.webp",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s6",
    title: "週末ホールディングス",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 12:35〜13:05",
    description: "正直言って、漫才です。",
    image_url: "/images/stage/s6.webp",
    category: "indoor",
    day: 1,
  },
  {
    project_id: "s7",
    title: "IRIS blue",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 13:00〜13:20",
    description: "ナガタソングとスイブステップ",
    image_url: "/images/stage/s7.webp",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s8",
    title: "音楽部",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 13:20〜14:20\n【2日目】 11:45〜12:45",
    description: "本格的な合唱曲からみんな知ってるJpopまで！文化祭の喧騒を離れて私たちの音楽に耳を傾けてみてはいかがですか？。",
    image_url: "/images/stage/s8.webp",
    category: "indoor",
    day: "both",
  },
  {
    project_id: "s9",
    title: "Copy Cat",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【1日目】 14:35〜15:00",
    description: "一日目ラスト。最高に盛り上げます！",
    image_url: "/images/stage/s9.webp",
    category: "outdoor",
    day: 1,
  },
  {
    project_id: "s10",
    title: "書道部（パフォーマンス）",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【2日目】 9:20〜9:40",
    description: "墨飛び注意!!書道パフォーマンスは一般祭9:20〜9:40🌟\n展示では書道部員渾身の作品たちだけでなく、グラス、うちわの販売やうちわ作り体験もやっています！",
    image_url: "/images/stage/s10.webp",
    category: "indoor",
    day: 2,
  },
  {
    project_id: "s11",
    title: "こしあねん",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 9:30〜9:50",
    description: "正体不明（音楽部）のバンド、\nその正体はいかに、、？",
    image_url: "/images/stage/s11.webp",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s12",
    title: "nanala",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 10:20〜10:40",
    description: `"君に笑顔の向日葵咲かせたい。"\nあの有名ソングをシャッフルボーカルでお届け🌻\nぜひぜひ足を運んでくださーい！！！"`,
    image_url: "/images/stage/s12.webp",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s13",
    title: "ダンス部",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 11:05〜11:45",
    description: "あなたの心、弾ませる。\nダンスで魅せる最高のひととき！",
    image_url: "/images/stage/s13.webp",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s14",
    title: "Traverse",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 12:45〜13:05",
    description: "Q.あなたはなぜステージに登るのですか？\nA.なぜって？そこにステージがあるからさ\ntips: 🥂😆　💖⚔️　💎🏝️　🧑‍🤝‍🧑💞",
    image_url: "/images/stage/s14.webp",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s15",
    title: "Ousia",
    type: "野外ステージ",
    location: "野外ステージ",
    schedule: "【2日目】 14:05〜14:30",
    description: "大トリを務めますOusia(ウーシア)です！！！文化祭の最後に最高に盛り上がれるステージにするので、みんなきてください🫵🫵",
    image_url: "/images/stage/s15.webp",
    category: "outdoor",
    day: 2,
  },
  {
    project_id: "s16",
    title: "Lien",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【1日目】 14:35〜14:55",
    description: "1日限りのダンスステージ！！\nぜひ来てください！\nLet’s enjoy with us!!",
    image_url: "/images/stage/s16.webp",
    category: "indoor",
    day: 2,
  },
  {
    project_id: "s17",
    title: "Milky♡Quint",
    type: "講堂ステージ",
    location: "講堂ステージ",
    schedule: "【2日目】 14:15〜14:30",
    description: "5人組アイドルステージ✨\n今日限りの最強可愛いミニライブぜひ見に来てください！！",
    image_url: "/images/stage/s17.webp",
    category: "indoor",
    day: 2,
  },
];