// app/display/data.ts

export const DISPLAY_PROJECTS = [
  {
    project_id: "d1",
    title: "茶華道部",
    type: "展示",
    location: "3F 家庭準備室・作法室",
    floor_number: 3,
    description: "お茶とお花の素敵な世界。日本の伝統文化に触れてみませんか？",
    image_url: "/images/display/d1.png",
  },
  {
    project_id: "d2",
    title: "数学部",
    type: "展示",
    location: "2F 203教室",
    floor_number: 2,
    description: "数学のパズルに挑戦！数学の楽しさを体験してください。",
    image_url: "/images/display/d2.png",
  },
  {
    project_id: "d3",
    title: "図書委員会",
    type: "展示",
    location: "2F 204教室",
    floor_number: 2,
    description: "本の魅力を再発見！おすすめ本紹介やしおり製作など。",
    image_url: "/images/display/d3.png",
  },
  {
    project_id: "d4",
    title: "写真部",
    type: "展示",
    location: "2F 205教室",
    floor_number: 2,
    description: `部員が撮影した写真の展示・販売を行います！\n他部活とのコラボ展示もあり！見逃すな！`,
    image_url: "/images/display/d4.png",
  },
  {
    project_id: "d5",
    title: "新聞委員会",
    type: "展示",
    location: "2F 204教室",
    floor_number: 2,
    description: "最近の学校ニュースを深掘り！春高祭の「今」をお届けします。",
    image_url: "/images/display/d5.png",
  },
  {
    project_id: "d6",
    title: "物理部",
    type: "展示",
    location: "2F 203教室",
    floor_number: 2,
    description: "Shall we Quiz?",
    image_url: "/images/display/d6.png",
  },
  {
    project_id: "d7",
    title: "漫画研究部",
    type: "展示",
    location: "3F 302教室",
    floor_number: 3,
    description: "ここだけの部誌やポストカード、シールを販売中!!\n2コマ大喜利などの体験コーナーや展示コーナーも盛りだくさん用意しています",
    image_url: "/images/display/d7.png",
  },
  {
    project_id: "d8",
    title: "文芸部",
    type: "展示",
    location: "3F 303教室",
    floor_number: 3,
    description: "文字が織りなす、文芸の世界へ。部誌の販売と作品展示を行います。",
    image_url: "/images/display/d8.png",
  },
  {
    project_id: "d9",
    title: "美術部",
    type: "展示",
    location: "3F 306教室",
    floor_number: 3,
    description: "個性豊かな部員による独創的なアート作品の数々。",
    image_url: "/images/display/d9.png",
  },
  {
    project_id: "d10",
    title: "家庭部",
    type: "展示",
    location: "3F 306教室",
    floor_number: 3,
    description: "シュシュやくるみボタンの髪飾りの販売、\nアロマサシェの手作り体験をします！\nさらに中3生限定受験必勝お守りを5個限定で販売！\nぜひ来てください！",
    image_url: "/images/display/d10.png",
  },
  {
    project_id: "d11",
    title: "書道部",
    type: "展示",
    location: "4F 404教室",
    floor_number: 4,
    description: "迫力の墨蹟をご覧あれ。伝統と革新が融合した墨の世界。",
    image_url: "/images/display/d11.png",
  },
  {
    project_id: "d12",
    title: "ESS部",
    type: "展示",
    location: "4F 405教室",
    floor_number: 4,
    description: "Enjoy English! 英語で楽しくコミュニケーションしましょう。",
    image_url: "/images/display/d12.png",
  },
  {
    project_id: "d13",
    title: "生物部",
    type: "展示",
    location: "4F 406教室",
    floor_number: 4,
    description: "校内に潜む生き物たちの生態を観察。生命の不思議に迫ります。",
    image_url: "/images/display/d13.png",
  },
];