// app/display/data.ts

export const DISPLAY_PROJECTS = [
  {
    project_id: "d1",
    title: "茶華道部",
    type: "展示",
    location: "3F 家庭準備室・作法室",
    floor_number: 3,
    description: "お茶とお花の素敵な世界。日本の伝統文化に触れてみませんか？",
    image_url: "/images/display/d1.webp",
  },
  {
    project_id: "d2",
    title: "大学「の」数学 (数学部)",
    type: "展示",
    location: "2F 203教室",
    floor_number: 2,
    description: "時間帯に応じて、3つのトピックをゼミ形式でお話します。\nトピック群\n(グラフ理論、線形代数、群論)",
    image_url: "/images/display/d2.webp",
  },
  {
    project_id: "d3",
    title: "図書委員会",
    type: "展示",
    location: "2F 204教室",
    floor_number: 2,
    description: "本の魅力を再発見！おすすめ本紹介やしおり製作、ラベンダーサシェの販売などを行っています🪻静かな空間で一休みしませんか？",
    image_url: "/images/display/d3.webp",
  },
  {
    project_id: "d4",
    title: "写真部",
    type: "展示",
    location: "2F 205教室",
    floor_number: 2,
    description: `部員が撮影した写真の展示・販売を行います！\n他部活とのコラボ展示もあり！見逃すな！`,
    image_url: "/images/display/d4.webp",
  },
  {
    project_id: "d5",
    title: "新聞委員会",
    type: "展示",
    location: "2F 204教室",
    floor_number: 2,
    description: "最近の学校ニュースを凝縮！長田高校の「今」をお届けします。\n「新聞離れ」が進んでいる今、新聞の魅力を伝えたい。\n新聞の世界へ、どっぷり浸ってください！。",
    image_url: "/images/display/d5.webp",
  },
  {
    project_id: "d6",
    title: "物理部(クイズ研究会)",
    type: "展示",
    location: "2F 203教室",
    floor_number: 2,
    description: "長田高校クイズ研究会、略してNQLです。物理はやってないです。\nShall we Quiz?",
    image_url: "/images/display/d6.webp",
  },
  {
    project_id: "d7",
    title: "漫画研究部",
    type: "展示",
    location: "3F 302教室",
    floor_number: 3,
    description: "ここだけの部誌やポストカード、シールを販売中!!\n2コマ大喜利などの体験コーナーや展示コーナーも盛りだくさん用意しています",
    image_url: "/images/display/d7.webp",
  },
  {
    project_id: "d8",
    title: "文芸部",
    type: "展示",
    location: "3F 303教室",
    floor_number: 3,
    description: "文字が織りなす、文芸の世界へ。部誌の販売と作品展示を行います。",
    image_url: "/images/display/d8.webp",
  },
  {
    project_id: "d9",
    title: "美術部",
    type: "展示",
    location: "3F 306教室",
    floor_number: 3,
    description: "美術部員による絵の展示と、ポストカードの販売、アルコールインクアート体験を実施しています！",
    image_url: "/images/display/d9.webp",
  },
  {
    project_id: "d10",
    title: "家庭部",
    type: "展示",
    location: "3F 306教室",
    floor_number: 3,
    description: "シュシュやくるみボタンの髪飾りの販売、\nアロマサシェの手作り体験をします！\nさらに中3生限定受験必勝お守りを5個限定で販売！\nぜひ来てください！",
    image_url: "/images/display/d10.webp",
  },
  {
    project_id: "d11",
    title: "書道部",
    type: "展示",
    location: "4F 404教室",
    floor_number: 4,
    description: "墨飛び注意!!書道パフォーマンスは一般祭9:20〜9:40🌟\n展示では書道部員渾身の作品たちだけでなく、グラス、うちわの販売やうちわ作り体験もやっています！",
    image_url: "/images/display/d11.webp",
  },
  {
    project_id: "d12",
    title: "ESS部",
    type: "展示",
    location: "4F 405教室",
    floor_number: 4,
    description: "海外のお菓子を売ってます！ \nEnjoy English! 英語で楽しくコミュニケーションしましょう！",
    image_url: "/images/display/d12.webp",
  },
  {
    project_id: "d13",
    title: "生物部",
    type: "展示",
    location: "4F 406教室",
    floor_number: 4,
    description: "「チリメンモンスター探し」の体験をやります！映える瓶の販売もしてます！剥製や標本、さらにはドクターフィッシュも展示しています。ぜひお越しください！",
    image_url: "/images/display/d13.webp",
  },
];